### ISSUE TITLE
Restyle "login" form

### ISSUE THREAD

**Issue by Crabar** [drinkit/ember-client#10]

**Comment by fotografira** [comment]
Косметические улучшения:

![image](https://cloud.githubusercontent.com/assets/17004110/13085438/fadd878e-d4e6-11e5-8706-9f1bf7e85a89.png)

**Comment by Crabar** [comment]
Is it normal that buttons' color is green? Green isn't a part of our style design as I know.

P.S. Sorry for English, I'm just trying to have more practice :).

**Comment by fotografira** [comment]
Here is our button design:

![image](https://cloud.githubusercontent.com/assets/17004110/13146225/6015b244-d65d-11e5-8b52-892959d451e7.png)

**Comment by Crabar** [comment]
Srsly? Eh... I totally forgot about it... Sorry, my mistake.
