### ISSUE TITLE
Restyle "ingredients filter" component

### ISSUE THREAD

**Issue by Crabar** [drinkit/ember-client#8]
Now it looks like a crap. So it will be great to work on it's design.

**Comment by fotografira** [comment]
Проверяла сдвиг крестика в фотошопе. я думаю, там есть сдвиг на 0,5 рх:
![image](https://cloud.githubusercontent.com/assets/17004110/12887064/8ffd351c-ce7a-11e5-94d1-e58790d4b404.png)

**Comment by Crabar** [comment]
Возможно нужно убрать сглаживание шрифта для этого крестика. Попробую.

**Comment by fotografira** [comment]
Да, если можно поставить только крестик без сглаживания, думаю, будет нормально.

Ниже пример улучшений по дизайну компонента:

![image](https://cloud.githubusercontent.com/assets/17004110/12914971/524b6c64-cf30-11e5-8cd3-3e5930a3a7cd.png)

**Comment by Crabar** [comment]
Есть нюансы. Из-за особенностей работы моего бара я убрал возможность удалить ингриедиент прямо из списка. Также я сделал крестик более похожим на крестик со старой версии. Отступы сделал как у тебя. Стрелочку я не менял, так как внешний вид скрол (и его наличие) зависит от браузера и ОС. Например, в хроме на маке скрола нет вообще.

**Comment by Crabar** [comment]
Насчет сдвига крестика. Опытным путем я выяснил, что это связано со шрифтом CenturyGothic. Если поставить sans-serif на всю надпись (и название, и крестик) эти сдвиги исчезают. Только на крестик недостаточно. Поэтому надо или смирится, или менять шрифт.

**Comment by fotografira** [comment]
Пример всей формы с доработками

![drinkit-main](https://cloud.githubusercontent.com/assets/17004110/12979320/01cae714-d0df-11e5-8c73-a823fd78f684.png)

**Comment by Crabar** [comment]
@fotografira Moved last to #29
